### ISSUE TITLE
Gitcoin Grants Round 10: Bitcoin Yield Sources Analysis - DRAFT

### ISSUE THREAD

**Issue by jon-tompkins** [Badger-Finance/gitcoin#7]
Badger works very closely with projects all across DeFi to find the best yield on BTC deposits and bring it to our users.  With current and upcoming vault strategies we feel pretty confident that we have access to most of the best DeFi native yield sources.  What we would like to have a better understanding of is ALL of the places where anyone is earning interest on Bitcoin at scale.  Anywhere there is better than 5% yield on $10million worth or more of Bitcoin we want to know about it.  The winner will put together the best analysis of BTC yield sources DeFi and non-DeFi native.  The high level goal is to identify these yield sources, and if some exist and are not being captured by DeFi currently see if we can capture them through some bridge or in incubating a project to provide the same service in DeFi.

**Comment by Tritium-VLK** [comment]
Baked into honypot
